services:
  api-gateway:
    image: nginx:stable-alpine
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    ports:
      - 8080:8080
    deploy:
      replicas: 1
    volumes:
      - ./nginx_configuration/fastcgi_params:/etc/nginx/conf.d/fastcgi_params
      - ./nginx_configuration/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static_files:/files
  qgis-server:
    image: opengisch/qgis-server:3.28.4-jammy
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      SKIP_NGINX: true
      QGIS_SERVER_PARALLEL_RENDERING: true
      QGIS_SERVER_MAX_THREADS: 4
      QGIS_SERVER_LOG_LEVEL: 0
      QGIS_SERVER_WMS_MAX_HEIGHT: 10000
      QGIS_SERVER_WMS_MAX_WIDTH: 10000
      QGIS_SERVER_IGNORE_BAD_LAYERS: 1
    volumes:
      - ./qgis_server_data:/io/data
